name: 'aws code artifcats'
description: 'build & upload package to aws code artifact'

inputs:
  aws_region: 
    description: 'aws region'
    required: true
    default: 'us-east-1'
  aws_codeartifact_domain:
    description: 'aws code artifcats login credentials'
    required: true
  aws_codeartifact_domain_owner:
    description: 'aws code artifcats login credentials'
    required: true
  aws_codeartifact_repository:
    description: 'aws code artifcats login credentials'
    required: true
  build_file_path:
    description: 'build file path *.tar.gz'
    deafult: "dist/*.tar.gz"

runs:
  using: "composite"
  steps:

    - id: 'configure-twine'
      run: aws codeartifact login --tool twine --domain ${{inputs.aws_codeartifact_domain}} --domain-owner ${{inputs.aws_codeartifact_domain_owner}} --repository ${{inputs.aws_codeartifact_repository}} --region ${{inputs.aws_region}}
      shell: bash

    - id:  'package-to-code-artifacts'
      run: twine upload --repository codeartifact ${{inputs.build_file_path}}